### ISSUE TITLE
Email and username behavior correction on frontend

### ISSUE THREAD

**Issue by krcpr007** [Training-and-Placement-Cell-NIT-Patna/tnpcell-portal#13]
@Sahityaaryan do the sidebar changes for coordinators and students as well.

**Comment by tnpcell-nitp** [comment]
@Sahityaaryan 
![image](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/140609818/baabef1f-956b-44a9-a8db-43fac8d36e2e)
Keep your text align to the profile picture 
Don't Do like this :-
![image](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/140609818/0dc48f0c-f161-45a3-b992-484b277c89ea)
