### ISSUE TITLE
Add Debarred option

### ISSUE THREAD

**Issue by krcpr007** [Training-and-Placement-Cell-NIT-Patna/tnpcell-portal#19]
An option for students who are eligible for training and placement cell.
option will be added just like approved and rejected which are already there.

**Comment by Sahityaaryan** [comment]
is it "details" or literally a  "debarred" ?

**Comment by krcpr007** [comment]
> is it "details" or literally a "debarred" ?

Yeah literally a debarred option. I'll  add it don't worry
