### ISSUE TITLE
New Coverpage Navbar 

### ISSUE THREAD

**Issue by krcpr007** [Training-and-Placement-Cell-NIT-Patna/tnpcell-portal#44]
@Sahityaaryan can you create one of the following responsive navbars using tailwind CSS
![image](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/80947662/b1b18aa3-912a-42c4-9c85-7d65f163767f)
![image](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/80947662/57cda767-92df-4b91-a790-34158791e54c)
![image](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/80947662/078be1d6-7066-4834-9d0f-3fac625411d6)
![image](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/80947662/0faa1e61-050c-429e-879a-b002accc777d)
Ref:-
https://reflect.app/home?ref=godly
https://10xdesigners.co/?ref=godly
https://10xdesigners.co/?ref=godly
https://www.cosmos.so/
https://www.samara.com/?ref=godly

**Comment by Sahityaaryan** [comment]
Yes

**Comment by krcpr007** [comment]
@Sahityaaryan PR??
