### ISSUE TITLE
Style : Improve the style of Student registrations form

### ISSUE THREAD

**Issue by krcpr007** [Training-and-Placement-Cell-NIT-Patna/tnpcell-portal#51]
![image](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/80947662/1e3b4e59-7d69-4f44-83e3-75a768ef8497)
@Sahityaaryan improve the registration from style.
make the form section like
in personal details Address should be a another section 
in the academic details, cgpa should be another section 10th and 12th should be in the other section
if you don't understand contact me

PS: Don't change the constraints in input filed

**Comment by Sahityaaryan** [comment]
I will do it
