### ISSUE TITLE
Style: small fix in landing page

### ISSUE THREAD

**Issue by krcpr007** [Training-and-Placement-Cell-NIT-Patna/tnpcell-portal#60]
![Screenshot_20231005-011347](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/80947662/0051a9d5-3a00-4a00-80d0-2c986b3efc37)
See the text typewriter position correct it in the mobile view

**Comment by Sahityaaryan** [comment]
it is fixed, for more optimization please share the testing dimensions.

**Comment by Sahityaaryan** [comment]
<img width="960" alt="image" src="https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/115429795/86196eb6-b233-47c1-9456-6ec612082f21">

Here is the image

**Comment by krcpr007** [comment]
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/115429795/276873437-86196eb6-b233-47c1-9456-6ec612082f21.png">
> Here is the image

okay I'll recheck
