### ISSUE TITLE
Style: technical team page profile card 

### ISSUE THREAD

**Issue by krcpr007** [Training-and-Placement-Cell-NIT-Patna/tnpcell-portal#61]
Correct the style of technical team members card 
![Screenshot_20231005-011436](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/80947662/2e62f70a-b55b-489f-aed6-203b9330de09)

**Comment by Sahityaaryan** [comment]
I am unclear at styling?
Do I have to reduce the width of the cards?

**Comment by Sahityaaryan** [comment]
<img width="598" alt="image" src="https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/115429795/0811b325-12ad-40ef-8593-424b4b2e4a3a">


Or whether the misfitting of the card's picture at some screen size like one above?

**Comment by krcpr007** [comment]
> <img alt="image" width="598" src="https://user-images.githubusercontent.com/115429795/276875504-0811b325-12ad-40ef-8593-424b4b2e4a3a.png">
> Or whether the misfitting of the card's picture at some screen size like the one above?

yes misfitting of card's picture
