### ISSUE TITLE
Fix : Student's details (Read description)

### ISSUE THREAD

**Issue by krcpr007** [Training-and-Placement-Cell-NIT-Patna/tnpcell-portal#65]
![image](https://github.com/Training-and-Placement-Cell-NIT-Patna/tnpcell-portal/assets/80947662/adefbbb1-fe5e-4540-a216-8e35245ed4a0)
If the student is not PWD then the following options should not show (in front-end) in the student details
1. Type Of Disability (If PWD)
2. Type Of Disability (If PWD)
3. Disability Certificate (IF PWD)

Note: same for the category as well, if the student is general then the category certificate and certificate link should not displayed on frontend

**Comment by krcpr007** [comment]
@Sahityaaryan look into this

**Comment by Sahityaaryan** [comment]
Sure sir

**Comment by Sahityaaryan** [comment]
Sir I think this feature is already been implemented
